### ISSUE TITLE
Shown as Expected but fails to Add/Update on an Entity One-on-One Relation

### ISSUE THREAD

**Issue by apklein** [alejandro-du/crudui#10]
I have a similar problem to this one: [https://vaadin.com/forum/#!/thread/571301/571300]

the grid works as expected, the form is shown as expected, but when I do click on Update/Add Button I receive the "com.vaadin.data.util.MethodProperty$MethodException" doing invokeSetMethod

UserAccount->Person and doing getPerson() on the instance it returns null. What maybe I'm doing wrong here?

**Comment by alejandro-du** [comment]
@apklein Hope you have tried what that thread suggested. But it's hard to say without seeing your code. Are you able to publish a minimal example to reproduce the issue?
