### ISSUE TITLE
External notifications

### ISSUE THREAD

**Issue by urkl** [alejandro-du/crudui#11]
Hi Alejandro, as an idea, it would be nice, to add a possibility to externelize notifications, or to overide them.

**Comment by alejandro-du** [comment]
Hi, that's true. I thought about removing the notifications altogether as it should be possible to manually add them in the CRUD listener implementations. However, I want to provide as much out-of-the-box functionality as possible, so maybe a method such as `setNotificationsVisible(boolean)` would be a better idea.

**Comment by urkl** [comment]
Your idea is definitely better. 
And another question/idea would be implementing inline grid editor?
Have you ever thought about it?

**Comment by alejandro-du** [comment]
I thought about it but discarded it. There wouldn't be much for the add-on to offer because the Grid itself has the required features.

**Comment by alejandro-du** [comment]
Fixed for `GridCrud`. Call ´showNotifications(false)` to disable notifications or override `GridCrud.showNotification(String)` to provide a custom implementation.
