### ISSUE TITLE
If Update Action throws IllegalArgumentException Exception is swallowed

### ISSUE THREAD

**Issue by dwlabcube** [alejandro-du/crudui#113]
If the Action in Line 193 throws an IllegalArgumentException (for reasons that are within the updateOperation (for Example an Enum-Entry can not be found by Name or whatever custom logic might throw an IllegalArgumentException) then it simply disappears.

![image](https://user-images.githubusercontent.com/46682038/189053635-cb2b3d70-9d84-4c6e-a30a-6504dd4bbe76.png)

I am sure that line of code is there for a reason, but maybe one should catch a more specific Exception instead all IllegalArgumentException in that line. Otherwise Exceptions thrown by DatabasePersistence or Processing the UpdateOperation are just swalloed and the user thinks everything is saved.

**Comment by alejandro-du** [comment]
Good catch! I'll have to look at it at some point. Or if someone has time to investigate this and contribute a patch, welcome!
