### ISSUE TITLE
Problem when using the MultiSelectListBox (vaadin) component

### ISSUE THREAD

**Issue by Shotty1984** [alejandro-du/crudui#114]
I think me need help, I'm trying to use MultiSelectListBox component in CRUD UI, but I get an error when return multiSelectListBox through FieldProvider.

my test example:

```
crud.getCrudFormFactory().setFieldProvider("nameGroup", o -> {
    MultiSelectListBox<String> multiSelectListBox = new MultiSelectListBox<>();
    List<String> items = new ArrayList<>(Arrays.asList("group1", "group2", "group3"));
    multiSelectListBox.setItems(items);
    return multiSelectListBox;
});
```

after return multiSelectListBox:

**java.lang.RuntimeException: com.vaadin.flow.data.binder.BindingException: An exception has been thrown inside binding logic for the field element [style='width:100%', multiple='true', readonly='true']**

**Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Set (java.lang.String and java.util.Set are in module java.base of loader 'bootstrap')**

When use simple ComboBox work ok, but me needed multiselect combobox :(, What am I doing wrong?

**Comment by alejandro-du** [comment]
Try returning a `Set` instead of an `ArrayList`.

**Comment by alejandro-du** [comment]
Are you able to provide a minimal runnable project so I can reproduce the issue?

**Comment by alejandro-du** [comment]
Closing this. If you still have the issue, please comment and provide more information and details.
