### ISSUE TITLE
Dynamically change fields in FormFactory

### ISSUE THREAD

**Issue by karakal** [alejandro-du/crudui#120]
I have a Form that has two fields: filter and parameter:
![image](https://github.com/alejandro-du/crudui/assets/2448293/cac8c31a-7ea1-418a-a434-d7439c96c276)
Depending on the choosen value in the parameter combobox the filter field should be a textfield or a combox.
I defined a FieldProvider that does that perfectly when I open a new form:
![image](https://github.com/alejandro-du/crudui/assets/2448293/7f0793d8-a738-4488-88ec-06e20ca0a488)

I also implemented another fieldprovider, that has a ValueChangeListener on the parameter-combobox, to set some helper-text and it should also trigger the fieldprovider of the filter-field to change the filter field.

Is there a possibility to do this easily? For example to trigger the fieldprovider of the filter-field to replace the field already in the form?

**Comment by alejandro-du** [comment]
I think the best option here is to implement a custom field with all the components that you need.
