### ISSUE TITLE
Very technical error messages when using JSR 380 bean validation.

### ISSUE THREAD

**Issue by tbee** [alejandro-du/crudui#121]
I've implemented a custom validation:
`@PersonPasswordValidator(message="Password cannot be empty")
`

This works fine, but the message shown in crudui is mixed in with a lot of technical stuff:

`Validation failed for classes [nl.softworks.selfroster.domain.entity.Person] during persist time for groups [jakarta.validation.groups.Default, ] List of constraint violations:[ ConstraintViolationImpl{interpolatedMessage='Password cannot be empty', propertyPath=, rootBeanClass=class nl.softworks.selfroster.domain.entity.Person, messageTemplate='Password cannot be empty'} ConstraintViolationImpl{interpolatedMessage=' cannot be empty', propertyPath=rawPassword, rootBeanClass=class nl.softworks.selfroster.domain.entity.Person, messageTemplate='{jakarta.validation.constraints.NotNull.message}'} ]
`

How do I get crudui to only show the message(s)?

**Comment by alejandro-du** [comment]
Are you able to provide a **minimal** runnable project that I can use to reproduce the issue?

**Comment by alejandro-du** [comment]
Closing this. If you still have the issue, please feel free to comment with additional information and details.

**Comment by tbee** [comment]
The issues turned out not to be with CrudUI 👍

**Comment by alejandro-du** [comment]
Thanks for letting us know.
