### ISSUE TITLE
CrudFormFactory is missing setButtonCaption

### ISSUE THREAD

**Issue by LuboZ** [alejandro-du/crudui#132]
Hi, i would like to rename buttons in dialog, but missing setButtonCaption method.
Also please how can i rename header text of the dialog ?

Thank you

**Comment by alejandro-du** [comment]
For button captions, you need a reference to a concrete implementation of `CrudFormFactory`. Then you can call the appropriate method. For example:

```java
var formFactory = new DefaultCrudFormFactory(User.class);
formFactory.setButtonCaption(CrudOperation.ADD, "Add new user");
```

Similarly, for form captions, you need a concrete implementation of `CrudLayout`. Then you can call the appropriate method. For example:

```Java
var layout = new VerticalCrudLayout();
layout.setFormCaption(CrudOperation.UPDATE, "Update user");
```

**Comment by LuboZ** [comment]
Thank you very much 👍
