### ISSUE TITLE
Validation doesn't work on TextArea + Enter

### ISSUE THREAD

**Issue by mgodbole** [alejandro-du/crudui#137]
Hi @alejandro-du I am using the crudui (awesome add-on, Thank you!) and have run into a snag.

I have a POJO with a field called note
```
    @Size(min = 0, max = 250, message = "Max 250 characters")
    private String note;
```

I wish to use a `TextArea` instead of the default `TextField`. So I configured the form using
```
        crud.getCrudFormFactory().setFieldProvider("note", entity -> {
            return new TextArea();
        });
```
And yes, I do have the validation turned on.
`form.setUseBeanValidation(true);
`

**Observation:**

1. The validation works correctly and POJO is updated if I click the "Update" button
2. But, if I hit `Enter`, the POJO remains unchanged

- This problem occurs **only** for the `TextArea`. 
- All other default fields rendered by the `CrudFormFactory` are working as expected if I hit `Enter`

**Comment by alejandro-du** [comment]
Could this be because `TextArea` allows <ENTER> as a character?

**Comment by mgodbole** [comment]
> Could this be because `TextArea` allows as a character?

I have never felt so stupid and ashamed in my life.
You are indeed right. Thank you

**Comment by alejandro-du** [comment]
No worries man. Good to know the issue was an "easy fix".
