### ISSUE TITLE
Error with grails 3 + vaadin 8 

### ISSUE THREAD

**Issue by frangelh** [alejandro-du/crudui#19]
grails=3.2.9
gorm=6.0.12.RELEASE
also ( vaadin-server 7.7.6 and 8.1.4, vaadin-compatibility,vaadin-client-compiled)
once I add the plugin to the dependency it gives me this error.
General error during conversion: java.lang.NoClassDefFoundError: com/vaadin/ui/Composite

**Comment by alejandro-du** [comment]
I don't think this is a problem with the add-on. Check your project configuration. It seems you are using the wrong version of Vaadin. Check also if the problem is with the grails integration.
