### ISSUE TITLE
isEmpty method

### ISSUE THREAD

**Issue by ekomrak** [alejandro-du/crudui#30]
Could you add the following method to the GridCrud class?
```java
public boolean isEmpty() {
    return CollectionUtils.isEmpty(items);
}
```
It will be very usefull method to do some logic if grid is empty.

**Comment by alejandro-du** [comment]
Sure, would you like to add it yourself and send a Pull Request? That way you'd become a contributor to this project :)

**Comment by alejandro-du** [comment]
Closing this since you can get the size of the underlying data provider as follows: `crud.getGrid().getDataProvider().size(new Query<>())`.
