### ISSUE TITLE
Permit set delete caption

### ISSUE THREAD

**Issue by adexerivera** [alejandro-du/crudui#40]
There is no option to change the alert message on delete operation, "Are you sure you want to delete this item?" as in the case of the rest of messages.

Would it be possible to access this message to update it?

**Comment by alejandro-du** [comment]
You can use the `AbstractTwoComponentsCrudLayout::setFormCaption`  or WindowBasedCrudLayout::setWindowCaption` methods to accomplish this.

**Comment by adexerivera** [comment]
Great @alejandro-du 

I was trying to make use of some of the functions that the add-on already has available, such as the `setValidationErrorMessage`.

Through your response I managed to solve the problem, here there are the code that solves it to me in case it could be useful to someone else.

```
HorizontalSplitCrudLayout crudLayout = new HorizontalSplitCrudLayout();
crudLayout.setFormCaption(CrudOperation.DELETE,"¿Estás segur@ que quieres eliminar este elemento?");
GridCrud<Certification> crud = new GridCrud<>(Certification.class, crudLayout);
```

Thanks
