### ISSUE TITLE
FieldProviders do not work with Vaadin 12

### ISSUE THREAD

**Issue by mrts** [alejandro-du/crudui#41]
`GridCrud` seems to mostly work in Vaadin 12, but `FieldProvider`s break.

For example, when using `ComboBoxProvider`, the following error occurs when you click on edit or add button:

```
java.lang.ClassCastException: 
  com.vaadin.flow.component.combobox.ComboBox 
  cannot be cast to com.vaadin.flow.data.binder.HasDataProvider
 at org.vaadin.crudui.form.impl.field.provider.AbstractListingProvider
  .buildField(AbstractListingProvider.java:42) ~[crudui-3.6.0.jar:3.6.0]
```

This is reproducible with `TestUI`.

**Comment by alejandro-du** [comment]
Thanks for reporting the issue. The problem was due to a change in the `ComboBox` hierarchy, so the add-on itself didn't compile with Vaadin 12+. Version 3.7.0 fixes the problem.

**Comment by mrts** [comment]
Thanks!
