### ISSUE TITLE
Bug when using crudui under app-layout (with minimal reproducible setup)

### ISSUE THREAD

**Issue by jflamy** [alejandro-du/crudui#45]
Here is a minimal setup to recreate a strange interaction that only happens with crudui (and not with a normal grid).  Since app-layout is likely what many people will be using ...

Steps to reproduce
•Clone https://github.com/jflamy/bug_crud.git
•Run mvn exec:java (or start org.ledocte.owlcms.Main from IDE)
•Click on the "Test" button -- observe there is no error message
•Refresh the page (navigating directly to the URL)
•Observe that there is an error message (cannot read property 'map' of null)

**Comment by alejandro-du** [comment]
Is this still a bug? The linked repo doesn't exist anymore.

**Comment by watho** [comment]
I think it is fixed upstream: https://github.com/vaadin/vaadin-grid-flow/issues/515

**Comment by alejandro-du** [comment]
Great. I'm closing this for now.
