### ISSUE TITLE
Grid is not rendered when GridCrud is used inside a Dialog

### ISSUE THREAD

**Issue by watho** [alejandro-du/crudui#48]
Steps to repoduce:

Add to your TestUI line 75 following code for a new tab with a button to open DefaultCrud inside Dialog
`addCrud(new Div(new Button("Open Dialog", e -> new Dialog(getDefaultCrud()).open())), "Windowed");`

See screenshot. The buttonBar is visible, but the grid not.

![screenshot_20190221_181750](https://user-images.githubusercontent.com/6670370/53188361-72c8a800-3605-11e9-8985-2645e4a86b66.png)

**Comment by alejandro-du** [comment]
The `Crud` component is configured to be size-full by default (the most comon use case). The `Dialog` component, on the other hand, is size-undefined by default. In order to visualize the `Crud` component, you have to set its size or set a defined size for the dialog. For example:

````
Crud<User> crud = new GridCrud<>(User.class);
Dialog dialog = new Dialog(crud);
dialog.setHeight("300px");
dialog.setWidth("600px");
dialog.open();
````

**Comment by alejandro-du** [comment]
Thanks for the [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve) example!
