### ISSUE TITLE
Lazy find all operation limits the use of provider to be of format generics DataProvider<T,Void> only instead of DataProvider<T,?>

### ISSUE THREAD

**Issue by boniechacha** [alejandro-du/crudui#54]
The interface  `LazyFindAllCrudOperationListene`r requires `DataProvider<T, Void>` on its `getDataProvider()` which prevents other implementations which does not use Void as a filter on the second generic. This could be resolved by making the interface be as:

```
public interface LazyFindAllCrudOperationListener<T> extends FindAllCrudOperationListener<T> {
    DataProvider<T, ?> getDataProvider();
}

```

Vaadin grid method for setting DataProvider requires DataProvider<T, ?> which I assume with the implementation above it will still work.

**Comment by alejandro-du** [comment]
Fixed. Thanks for the contribution!
