### ISSUE TITLE
flow-build-info.json shoudn't be included in JAR

### ISSUE THREAD

**Issue by jonmartinsolaas** [alejandro-du/crudui#56]
Caused by: java.io.IOException: Unable to create directory /Users/alejandro/git/crudui/target/frontend

Did not change anything other than pom.xml when updating from 3.9.0, which works fine, to 4.0.0.

**Comment by alejandro-du** [comment]
It seems to be related to this issue: https://github.com/vaadin/flow/issues/6336
I added a workaround in v4.0.1. Please let me know whether it works or not. Thanks for reporting!

**Comment by jonmartinsolaas** [comment]
4.0.2-SNAPSHOT works now, as far as I can see. Thx for quickfix :)
