### ISSUE TITLE
Cannot use custom crossfield validator annotations

### ISSUE THREAD

**Issue by nileshpandit009** [alejandro-du/crudui#57]
I have a custom cross-field validator `@StartEndDate` which checks if the end date is chronologically after the start date. The annotation has `@Target` as `ElementType.TYPE`.
I have `setUseBeanValidation(true)` on my `CrudFormFactory` but this validation doesn't even gets triggered.
I have tested different types of `@Target` and found out that, somehow, in crud ui, annotation that have `@Target({ElementType.FIELD})` only work. I need a cross-field validation functionality in my use case. Is there a way to do so?
Please help.

**Comment by sandronm** [comment]
@nileshpandit009 is it solved? Did you finally found how to deal with cross fields validation?
