### ISSUE TITLE
double click should always contain doubled-clicked row in selection

### ISSUE THREAD

**Issue by ldelaprade** [alejandro-du/crudui#61]
getGrid().addItemDoubleClickListener
(
    item
    ->
    {
                    // why should I have to test this ? double click should always contain
                    // doubled-clicked row in selection
                    if( item.getSource().getSelectedItems().iterator().hasNext() )
                    {
                        // do action on selected row

**Comment by alejandro-du** [comment]
I'm not sure I understand the issue. Are you sure this is a *crud-ui* issue? If so, can you please elaborate?
