### ISSUE TITLE
Add New NumberField, BigDecimalField and others

### ISSUE THREAD

**Issue by juanfranciscolopez28** [alejandro-du/crudui#62]
Thanks for your work.

When i add a number property, only show 3 decimals in form factory.

This is the grid
![imagen](https://user-images.githubusercontent.com/45214328/74183137-a6507800-4c44-11ea-8c66-01fcae263464.png)

This is the form
![imagen](https://user-images.githubusercontent.com/45214328/74183302-fdeee380-4c44-11ea-8397-ca906e6b6fef.png)

Can u add support to new Fields?
[https://vaadin.com/components/vaadin-text-field/java-examples/number-field](url)

Thanks you very much!

**Comment by DanielMartensson** [comment]
I have the same issue too.

**Comment by DanielMartensson** [comment]
> Thanks for your work.
> 
> When i add a number property, only show 3 decimals in form factory.
> 
> This is the grid
> ![imagen](https://user-images.githubusercontent.com/45214328/74183137-a6507800-4c44-11ea-8c66-01fcae263464.png)
> 
> This is the form
> ![imagen](https://user-images.githubusercontent.com/45214328/74183302-fdeee380-4c44-11ea-8397-ca906e6b6fef.png)
> 
> Can u add support to new Fields?
> [https://vaadin.com/components/vaadin-text-field/java-examples/number-field](url)
> 
> Thanks you very much!

Use this

```
	@Digits(integer=20, fraction=10)
	private BigDecimal sa0Max;
```

**Comment by alejandro-du** [comment]
Se #85.
