### ISSUE TITLE
Support TreeGrid

### ISSUE THREAD

**Issue by jflamy-dev** [alejandro-du/crudui#63]
Currently it is impossible to do 
```
        crud.setCrudListener(new LazyCrudListener<TeamTreeItem>() {
            @Override
            public DataProvider<TeamTreeItem, Void> getDataProvider() {
                return new TreeDataProvider<TeamTreeItem>(tbd);
            }
```
because of the Void generic.
Alternately, supporting the TreeGrid setItems method with the parent/child relationship would work.

**Comment by alejandro-du** [comment]
Thanks for reporting (and fixing, I guess?) https://github.com/alejandro-du/crudui/pull/64. Version 4.2.0 will fix the problem.
