### ISSUE TITLE
Does Addon suppot Uploading Images 

### ISSUE THREAD

**Issue by arnzel** [alejandro-du/crudui#73]
Hi does the addon support uploading images ? If yes can you add an example ?

Best Regards

Arne

**Comment by alejandro-du** [comment]
Hi, it should be possible by implementing a custom field. No examples at the moment. Btw, next time, please use the correct channels for questions:

- https://vaadin.com/directory/component/crud-ui-add-on/discussions
- https://alejandro.app.fi/crud-ui-demo/
