### ISSUE TITLE
Elements disappear in the autogenerated combo boxes

### ISSUE THREAD

**Issue by space** [alejandro-du/crudui#78]
Hi, thanks for the very good add-on.

I'm experimenting with some complex form and I've found an incorrect behavior / a bug (please tell me if this is the right place where to mention it): for all ComboBox in the new/edit form created by your add-on. Some elements in the list of the ComboBox, disappear when the user interacts deleting some characters of the selected element (it's possible because the combo box is an editable field) and then reopen the combo.

Here in attach an image of this behavior directly from your public demo (I discovered the problem on my code but I've been able to reproduce same error also in your demo).

![vaadin_crud_editor](https://user-images.githubusercontent.com/49166/95389616-5ec5dd00-08f4-11eb-9ecb-48d5cc0ca77f.png)

Please note that this problem doesn't happen with the normal ComboBox component used in a form created manually (without your component) and filled with a list of values of arbitrary size.

Thank you for response and again for all your contributions.

**Comment by alejandro-du** [comment]
Cannot reproduce. Maybe a Vaadin issue?

**Comment by sarawutwansee3-hue** [comment]
ไม่
