### ISSUE TITLE
Bug: Value's decimal removes when I look at them

### ISSUE THREAD

**Issue by DanielMartensson** [alejandro-du/crudui#85]
Hi!

I think this is a bug.
First I write this value.
![bild](https://user-images.githubusercontent.com/28505229/103570355-3f295b00-4ec9-11eb-833c-acc0eb4101a4.png)

Then I save. I can see the value.
![bild](https://user-images.githubusercontent.com/28505229/103570414-5700df00-4ec9-11eb-94c3-6f1dca0de147.png)

But when I reopen, this happens.
![bild](https://user-images.githubusercontent.com/28505229/103570447-654efb00-4ec9-11eb-897d-fb4d3f6b066c.png)

Why?
It's just a float variable in the entity. 
Also notice that in the field it's `,` (comma) and in the CRUD-row, it's `.` (dot)

**Comment by DanielMartensson** [comment]
Problem solved

```
	@Digits(integer=20, fraction=10)
	private BigDecimal sa0Max;
```

**Comment by alejandro-du** [comment]
It's probably not a bug. It's a [float precision](https://en.wikipedia.org/wiki/IEEE_754) issue. Use `BigDecimal` if you need arbitrary precision.
