### ISSUE TITLE
No longer compatible with Vaadin LTS

### ISSUE THREAD

**Issue by michaelknigge** [alejandro-du/crudui#98]
On https://vaadin.com/directory/component/crud-ui-add-on/overview there is a note under the screen shot:

**Note: This add-on is maintained only for the latest LTS version of Vaadin.**

Sadly this seems no longer be true. Today I updated to the latest Vaadin LTS 14.6.8 and also to crudui 4.6.0.  Sadly it does not work any longer. Than I've noticed commit 84ee66c874e6576119d497924416079419e321fc switches to Vaadin 20.0.0 

Is it desired to loose LTS compatibility? This would be very very sad :-(

Bye,
Michael

**Comment by alejandro-du** [comment]
I totally understand your concerns. What happened is that at some point I needed the crud-ui for current versions of Vaadin and I forgot to remove the note. As you can imagine making promises on maintenance is tricky for this kind of project (I work on it during my free time).

Have you tried with crud-ui versions 4.4.1 or 4.4.0?

**Comment by alejandro-du** [comment]
Hi, since Vaadin [changed](https://vaadin.com/blog/a-simpler-release-model) the release model, I should be able to keep the add-on compatible with the latest version from now on, which will be also the LTS version. Version 6.0.0 of the add-on supports Vaadin 23.
